### ISSUE TITLE
Box86 for other ARM64 64bits Linux platform like termux with -DBAD_SIGNAL=ON

### ISSUE THREAD

**Issue by xDoge26** [ryanfortner/box86-debs#2]
https://github.com/ptitSeb/box86/blob/master/docs/COMPILE.md#for-other-arm64-64bits-linux-platform

**Comment by ryanfortner** [comment]
The current method I use to push daily builds is through an armhf container. I'm 99% sure you can't compile arm64 stuff through armhf, so unfortunately for now I can't publish native arm64 builds.

Eventually I might switch the daily build workflow to cross-compile box86, but until then, you'll just have to use multiarch:
```
sudo dpkg --add-architecture armhf && sudo apt-get update
# proceed to add the repo
sudo apt-get install box86:armhf
```

Feel free to let me know if you have any questions.

**Comment by xDoge26** [comment]
Ok i will wait

**Comment by xDoge26** [comment]
Can you add -DBAD_SIGNAL=ON to generic build ?
It fixed pulse audio problem in termux proot/chroot
https://github.com/ptitSeb/box86/issues/775

**Comment by ryanfortner** [comment]
I just updated the workflow and I'm testing to see if it compiles successfully.

**Comment by ryanfortner** [comment]
Please check back in a  few hours and if the workflow completed successfully, there should be a new package in the repo called `box86-android` with the -DBAD_SIGNAL=ON flag.

**Comment by xDoge26** [comment]
thanks
