### ISSUE TITLE
legacy box86 package is still available

### ISSUE THREAD

**Issue by Botspot** [ryanfortner/box86-debs#7]
Running `apt search box86` showed your new naming convention for the rpi4arm64 box86 package, but it also showed that you still have the older `box86` package not yet deleted from the repo. This one appears to be an older version than the rest.
```
pi@raspberrypi:~ $ apt search box86
Sorting... Done
Full Text Search... Done
box86/unknown 0.3.1+20230322.3043f50-1 armhf
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

box86-android/unknown 0.3.1+20230323.1a0888c-1 armhf
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

box86-generic-arm/unknown 0.3.1+20230323.1a0888c-1 armhf
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

box86-rk3399/unknown 0.3.1+20230323.1a0888c-1 armhf
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

box86-rpi3arm64/unknown 0.3.1+20230323.1a0888c-1 armhf
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

box86-rpi4arm64/unknown,now 0.3.1+20230323.1a0888c-1 armhf [installed,automatic]
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

box86-tegrax1/unknown 0.3.1+20230323.1a0888c-1 armhf
  Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)

pi-apps-5f3374a7/now 1.0 all [installed,local]
  Dummy package created by pi-apps to install dependencies for the 'Box86' app
```
Perhaps this was intentional for backwards compatibility, but I just wanted to ensure you were aware of it.

**Comment by Botspot** [comment]
Same for box64.
```
box64/unknown 0.2.3+20230322.900f387-1 arm64
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)

box64-android/unknown 0.2.3+20230323.91a230b-1 arm64
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)

box64-generic-arm/unknown 0.2.3+20230323.91a230b-1 arm64
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)

box64-rk3399/unknown 0.2.3+20230323.91a230b-1 arm64
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)

box64-rpi3arm64/unknown 0.2.3+20230323.91a230b-1 arm64
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)

box64-rpi4arm64/unknown,now 0.2.3+20230323.91a230b-1 arm64 [installed,automatic]
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)

box64-tegrax1/unknown 0.2.3+20230323.91a230b-1 arm64
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)
```

**Comment by Rak1ta** [comment]
To the question of older versions. My armhf version above 0.2.9 does not start zoom. If it is possible to check and this is confirmed, you are asked to add this version to the author of the repository. Currently rolled back to the version from itai-nelken. Ryanfortner does not have this version for rollback. If this makes sense, then you can register in the description in pi-apps about the possibility of installing the old version of box86 if something does not work after the update. 
![Безымянный](https://user-images.githubusercontent.com/88277343/227765625-e5fb7117-9107-4de7-b594-b33f9de31cc9.png)

**Comment by ryanfortner** [comment]
To answer @Botspot 's question: I left old `box86` and `box64` builds behind just in case someone would need an older version. So yes, in other words, it was intentional for backwards-compatibility

@Rak1ta if box86 no longer starts zoom with the latest version, this is an issue in the software itself, and you'd need to [open an issue](https://github.com/ptitSeb/box86/issues/new/choose) on ptitseb's repo so that he can fix it. Otherwise, you'll just have to stick with itai's older deb.

**Comment by Botspot** [comment]
> To the question of older versions. My armhf version above 0.2.9 does not start zoom.

@Rak1ta, if you have some time to try this, could you upgrade to the latest box86 package, try launching zoom, and send the terminal output here?

**Comment by Rak1ta** [comment]
@Botspot Right now there is no way to double-check, but at the time the error occurred, the output was as such. Previously, this error was already slipping in the repositories a year ago. 
```
/home/pi/zoom/runzoom.sh: line 13: 31885 Segmentation fault box86 zoom "$1"
Zoom exited. Close this terminal to exit 
```
